from pptx import Presentation

def create_ppt(report_text):

    prs = Presentation()

    # Title Slide
    slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    slide.shapes.title.text = \
        "Research Report"

    slide.placeholders[1].text = \
        "Generated by Open Deep Research Agent"

    # Content Slides
    chunks = []

    for i in range(
        0,
        len(report_text),
        1000
    ):
        chunks.append(
            report_text[i:i+1000]
        )

    for chunk in chunks:

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        slide.shapes.title.text = \
            "Research Content"

        slide.placeholders[1].text = chunk

    ppt_file = "research_report.pptx"

    prs.save(ppt_file)

    return ppt_file